# Generated by Django 3.2 on 2022-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='country', max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(default='county', max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(default='postcode', max_length=254),
        ),
    ]
